### ISSUE TITLE
error while installing the examples dependency

### ISSUE THREAD

**Issue by muddlebee** [paritytech/asset-transfer-api#446]
Command : **npm run build:examples**

Error : 

> @substrate/asset-transfer-api@0.4.3 build:examples
> substrate-exec-rimraf examples/build/ && substrate-exec-tsc --project examples/tsconfig.json
> 
> 'substrate-exec-rimraf' is not recognized as an internal or external command,
> operable program or batch file.

OS : Windows 11
NodeJS : v20.17.0
Powershell

**Comment by marshacb** [comment]
fixed in release 0.4.4

**Comment by muddlebee** [comment]
hey @marshacb thank you for your help. 
Although im still getting the same error, do I need to install `substrate-exec-rimraf` explicitly? I just want to run the examples/script directly without setting up zombienet

**Comment by muddlebee** [comment]
my bad its working now with `yarn install` 
I was trying to run `npm i` instead 🤦
